#ifndef FULL_CHAIN_CONFIG_H
#define FULL_CHAIN_CONFIG_H

#ifndef WIFI_SSID
#define WIFI_SSID "weixin"
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD "88888888a"
#endif

#ifndef BACKEND_HOST
#define BACKEND_HOST "api.handemglsh.cloud"
#endif

#ifndef BACKEND_PORT
#define BACKEND_PORT 443
#endif

#ifndef BACKEND_USE_HTTPS
#define BACKEND_USE_HTTPS 1
#endif

#ifndef HARDWARE_ID
#define HARDWARE_ID "ESP32-HAND-001"
#endif

#ifndef BOARD_TOKEN
#define BOARD_TOKEN "esp32-secret"
#endif

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "1.1.0-emg-upload"
#endif

#ifndef FULL_CHAIN_HEARTBEAT_INTERVAL_MS
#define FULL_CHAIN_HEARTBEAT_INTERVAL_MS 1000u
#endif

#ifndef FULL_CHAIN_EMG_UPLOAD_INTERVAL_MS
#define FULL_CHAIN_EMG_UPLOAD_INTERVAL_MS 500u
#endif

#ifndef FULL_CHAIN_HTTP_TIMEOUT_MS
#define FULL_CHAIN_HTTP_TIMEOUT_MS 5000u
#endif

#ifndef FULL_CHAIN_WIFI_RECONNECT_INTERVAL_MS
#define FULL_CHAIN_WIFI_RECONNECT_INTERVAL_MS 3000u
#endif

#ifndef FULL_CHAIN_STM32_UART_BAUD
#define FULL_CHAIN_STM32_UART_BAUD 115200
#endif

#ifndef FULL_CHAIN_STM32_UART_TX_PIN
#define FULL_CHAIN_STM32_UART_TX_PIN 17
#endif

#ifndef FULL_CHAIN_STM32_UART_RX_PIN
#define FULL_CHAIN_STM32_UART_RX_PIN 18
#endif

#define STAGE6_STM32_UART_BAUD FULL_CHAIN_STM32_UART_BAUD
#define STAGE6_STM32_UART_TX_PIN FULL_CHAIN_STM32_UART_TX_PIN
#define STAGE6_STM32_UART_RX_PIN FULL_CHAIN_STM32_UART_RX_PIN

#endif
