#ifndef STAGE6_1C_INTEGRATION_CONFIG_H
#define STAGE6_1C_INTEGRATION_CONFIG_H

#include "../generated/controller_config.h"

/* Pipeline aliases used by the inherited Stage 5/6 inference sources. */
#define STAGE4_MODEL_FAMILY STAGE6_1C_MODEL_FAMILY
#define STAGE4_MODEL_SHA256_PREFIX STAGE6_1C_MODEL_PARAMETERS_SHA256
#define STAGE4_WINDOW_MS STAGE6_1C_WINDOW_MS
#define STAGE4_WINDOW_SAMPLES STAGE6_1C_WINDOW_SAMPLES
#define STAGE4_STEP_MS STAGE6_1C_STEP_MS
#define STAGE4_STEP_SAMPLES STAGE6_1C_STEP_SAMPLES
#define STAGE4_FEATURE_COUNT STAGE6_1C_FEATURE_COUNT
#define STAGE4_CLASS_COUNT STAGE6_1C_CLASS_COUNT
#define STAGE4_CHANNEL_COUNT STAGE6_1C_CHANNEL_COUNT
#define STAGE4_FIXED_BASELINE STAGE6_1C_FIXED_BASELINE
#define STAGE4_REST_LABEL STAGE6_1C_REST_LABEL

/* Inherited unchanged; Stage 6.1C training did not select controller parameters. */
#define STAGE4_MARGIN_THRESHOLD 3.0f
#define STAGE4_VOTE_HORIZON_MS 300u
#define STAGE4_VOTE_REQUIRED_FRACTION 0.70f
#define STAGE4_LOW_CONFIDENCE_HOLD_MS 200u

#endif
