#ifndef FULL_CHAIN_MODES_H
#define FULL_CHAIN_MODES_H

#define UART_ONLY_TEST 10
#define WIFI_ONLY_TEST 11
#define BLE_INFER_UART_TEST 12
#define FULL_CHAIN_SAFE_DEMO 13
#define FULL_CHAIN_WITH_EMG_UPLOAD 14

#ifndef FULL_CHAIN_MODE
#define FULL_CHAIN_MODE FULL_CHAIN_WITH_EMG_UPLOAD
#endif

#if FULL_CHAIN_MODE == UART_ONLY_TEST || FULL_CHAIN_MODE == BLE_INFER_UART_TEST || \
    FULL_CHAIN_MODE == FULL_CHAIN_SAFE_DEMO || FULL_CHAIN_MODE == FULL_CHAIN_WITH_EMG_UPLOAD
#define FULL_CHAIN_ENABLE_UART 1
#else
#define FULL_CHAIN_ENABLE_UART 0
#endif

#if FULL_CHAIN_MODE == WIFI_ONLY_TEST || FULL_CHAIN_MODE == FULL_CHAIN_SAFE_DEMO || \
    FULL_CHAIN_MODE == FULL_CHAIN_WITH_EMG_UPLOAD
#define FULL_CHAIN_ENABLE_WIFI 1
#else
#define FULL_CHAIN_ENABLE_WIFI 0
#endif

#if FULL_CHAIN_MODE == FULL_CHAIN_WITH_EMG_UPLOAD
#define FULL_CHAIN_ENABLE_EMG_UPLOAD 1
#else
#define FULL_CHAIN_ENABLE_EMG_UPLOAD 0
#endif

#endif
